
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("3f7d6b96-b044-4bd4-8cb2-b9d39bd47003")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("FACSHAREDModel", "FK__fac_autor__t_ida__1273C1CD", "fac_archivo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(fac_archivo), "fac_autorizacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(fac_autorizacion), True)>
<Assembly: EdmRelationshipAttribute("FACSHAREDModel", "FK__fac_hasta__h_ida__117F9D94", "fac_archivo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(fac_archivo), "fac_hastags", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(fac_hastags), True)>
<Assembly: EdmRelationshipAttribute("FACSHAREDModel", "FK__fac_autor__t_usu__1367E606", "fac_persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(fac_persona), "fac_autorizacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(fac_autorizacion), True)>
<Assembly: EdmRelationshipAttribute("FACSHAREDModel", "FK__fac_ranki__r_usu__108B795B", "fac_persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(fac_persona), "fac_ranking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(fac_ranking), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class FACSHAREDEntities
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto FACSHAREDEntities usando la cadena de conexión encontrada en la sección 'FACSHAREDEntities' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=FACSHAREDEntities", "FACSHAREDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto FACSHAREDEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "FACSHAREDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto FACSHAREDEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "FACSHAREDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_archivo() As ObjectSet(Of fac_archivo)
        Get
            If (_fac_archivo Is Nothing) Then
                _fac_archivo = MyBase.CreateObjectSet(Of fac_archivo)("fac_archivo")
            End If
            Return _fac_archivo
        End Get
    End Property

    Private _fac_archivo As ObjectSet(Of fac_archivo)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_autorizacion() As ObjectSet(Of fac_autorizacion)
        Get
            If (_fac_autorizacion Is Nothing) Then
                _fac_autorizacion = MyBase.CreateObjectSet(Of fac_autorizacion)("fac_autorizacion")
            End If
            Return _fac_autorizacion
        End Get
    End Property

    Private _fac_autorizacion As ObjectSet(Of fac_autorizacion)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_comentario() As ObjectSet(Of fac_comentario)
        Get
            If (_fac_comentario Is Nothing) Then
                _fac_comentario = MyBase.CreateObjectSet(Of fac_comentario)("fac_comentario")
            End If
            Return _fac_comentario
        End Get
    End Property

    Private _fac_comentario As ObjectSet(Of fac_comentario)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_hastags() As ObjectSet(Of fac_hastags)
        Get
            If (_fac_hastags Is Nothing) Then
                _fac_hastags = MyBase.CreateObjectSet(Of fac_hastags)("fac_hastags")
            End If
            Return _fac_hastags
        End Get
    End Property

    Private _fac_hastags As ObjectSet(Of fac_hastags)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_persona() As ObjectSet(Of fac_persona)
        Get
            If (_fac_persona Is Nothing) Then
                _fac_persona = MyBase.CreateObjectSet(Of fac_persona)("fac_persona")
            End If
            Return _fac_persona
        End Get
    End Property

    Private _fac_persona As ObjectSet(Of fac_persona)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property fac_ranking() As ObjectSet(Of fac_ranking)
        Get
            If (_fac_ranking Is Nothing) Then
                _fac_ranking = MyBase.CreateObjectSet(Of fac_ranking)("fac_ranking")
            End If
            Return _fac_ranking
        End Get
    End Property

    Private _fac_ranking As ObjectSet(Of fac_ranking)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_archivo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_archivo(ByVal fac_archivo As fac_archivo)
        MyBase.AddObject("fac_archivo", fac_archivo)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_autorizacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_autorizacion(ByVal fac_autorizacion As fac_autorizacion)
        MyBase.AddObject("fac_autorizacion", fac_autorizacion)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_comentario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_comentario(ByVal fac_comentario As fac_comentario)
        MyBase.AddObject("fac_comentario", fac_comentario)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_hastags. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_hastags(ByVal fac_hastags As fac_hastags)
        MyBase.AddObject("fac_hastags", fac_hastags)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_persona. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_persona(ByVal fac_persona As fac_persona)
        MyBase.AddObject("fac_persona", fac_persona)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet fac_ranking. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTofac_ranking(ByVal fac_ranking As fac_ranking)
        MyBase.AddObject("fac_ranking", fac_ranking)
    End Sub

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_archivo")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_archivo
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_archivo.
    ''' </summary>
    ''' <param name="a_idarchivo">Valor inicial de la propiedad a_idarchivo.</param>
    Public Shared Function Createfac_archivo(a_idarchivo As Global.System.String) As fac_archivo
        Dim fac_archivo as fac_archivo = New fac_archivo
        fac_archivo.a_idarchivo = a_idarchivo
        Return fac_archivo
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property a_idarchivo() As Global.System.String
        Get
            Return _a_idarchivo
        End Get
        Set
            If (_a_idarchivo <> Value) Then
                Ona_idarchivoChanging(value)
                ReportPropertyChanging("a_idarchivo")
                _a_idarchivo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("a_idarchivo")
                Ona_idarchivoChanged()
            End If
        End Set
    End Property

    Private _a_idarchivo As Global.System.String
    Private Partial Sub Ona_idarchivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_idarchivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_nombre_archivo() As Global.System.String
        Get
            Return _a_nombre_archivo
        End Get
        Set
            Ona_nombre_archivoChanging(value)
            ReportPropertyChanging("a_nombre_archivo")
            _a_nombre_archivo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_nombre_archivo")
            Ona_nombre_archivoChanged()
        End Set
    End Property

    Private _a_nombre_archivo As Global.System.String
    Private Partial Sub Ona_nombre_archivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_nombre_archivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_tipo_archivo() As Global.System.String
        Get
            Return _a_tipo_archivo
        End Get
        Set
            Ona_tipo_archivoChanging(value)
            ReportPropertyChanging("a_tipo_archivo")
            _a_tipo_archivo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_tipo_archivo")
            Ona_tipo_archivoChanged()
        End Set
    End Property

    Private _a_tipo_archivo As Global.System.String
    Private Partial Sub Ona_tipo_archivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_tipo_archivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_tamaño() As Nullable(Of Global.System.Decimal)
        Get
            Return _a_tamaño
        End Get
        Set
            Ona_tamañoChanging(value)
            ReportPropertyChanging("a_tamaño")
            _a_tamaño = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("a_tamaño")
            Ona_tamañoChanged()
        End Set
    End Property

    Private _a_tamaño As Nullable(Of Global.System.Decimal)
    Private Partial Sub Ona_tamañoChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub Ona_tamañoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_usuario() As Global.System.String
        Get
            Return _a_usuario
        End Get
        Set
            Ona_usuarioChanging(value)
            ReportPropertyChanging("a_usuario")
            _a_usuario = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_usuario")
            Ona_usuarioChanged()
        End Set
    End Property

    Private _a_usuario As Global.System.String
    Private Partial Sub Ona_usuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_link() As Global.System.String
        Get
            Return _a_link
        End Get
        Set
            Ona_linkChanging(value)
            ReportPropertyChanging("a_link")
            _a_link = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_link")
            Ona_linkChanged()
        End Set
    End Property

    Private _a_link As Global.System.String
    Private Partial Sub Ona_linkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_linkChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_detalle() As Global.System.String
        Get
            Return _a_detalle
        End Get
        Set
            Ona_detalleChanging(value)
            ReportPropertyChanging("a_detalle")
            _a_detalle = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_detalle")
            Ona_detalleChanged()
        End Set
    End Property

    Private _a_detalle As Global.System.String
    Private Partial Sub Ona_detalleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ona_detalleChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property a_archivo_b() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_a_archivo_b)
        End Get
        Set
            Ona_archivo_bChanging(value)
            ReportPropertyChanging("a_archivo_b")
            _a_archivo_b = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("a_archivo_b")
            Ona_archivo_bChanged()
        End Set
    End Property

    Private _a_archivo_b As Global.System.Byte()
    Private Partial Sub Ona_archivo_bChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub Ona_archivo_bChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_autor__t_ida__1273C1CD", "fac_autorizacion")>
     Public Property fac_autorizacion() As EntityCollection(Of fac_autorizacion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of fac_autorizacion)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_autorizacion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of fac_autorizacion)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_autorizacion", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_hasta__h_ida__117F9D94", "fac_hastags")>
    Public Property fac_hastags() As fac_hastags
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_hastags)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_hastags").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_hastags)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_hastags").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property fac_hastagsReference() As EntityReference(Of fac_hastags)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_hastags)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_hastags")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of fac_hastags)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_hastags", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_autorizacion")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_autorizacion
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_autorizacion.
    ''' </summary>
    ''' <param name="t_idarchivo">Valor inicial de la propiedad t_idarchivo.</param>
    ''' <param name="t_usuario">Valor inicial de la propiedad t_usuario.</param>
    ''' <param name="t_tipo">Valor inicial de la propiedad t_tipo.</param>
    Public Shared Function Createfac_autorizacion(t_idarchivo As Global.System.String, t_usuario As Global.System.String, t_tipo As Global.System.Int32) As fac_autorizacion
        Dim fac_autorizacion as fac_autorizacion = New fac_autorizacion
        fac_autorizacion.t_idarchivo = t_idarchivo
        fac_autorizacion.t_usuario = t_usuario
        fac_autorizacion.t_tipo = t_tipo
        Return fac_autorizacion
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property t_idarchivo() As Global.System.String
        Get
            Return _t_idarchivo
        End Get
        Set
            If (_t_idarchivo <> Value) Then
                Ont_idarchivoChanging(value)
                ReportPropertyChanging("t_idarchivo")
                _t_idarchivo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("t_idarchivo")
                Ont_idarchivoChanged()
            End If
        End Set
    End Property

    Private _t_idarchivo As Global.System.String
    Private Partial Sub Ont_idarchivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ont_idarchivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property t_usuario() As Global.System.String
        Get
            Return _t_usuario
        End Get
        Set
            If (_t_usuario <> Value) Then
                Ont_usuarioChanging(value)
                ReportPropertyChanging("t_usuario")
                _t_usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("t_usuario")
                Ont_usuarioChanged()
            End If
        End Set
    End Property

    Private _t_usuario As Global.System.String
    Private Partial Sub Ont_usuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ont_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property t_tipo() As Global.System.Int32
        Get
            Return _t_tipo
        End Get
        Set
            If (_t_tipo <> Value) Then
                Ont_tipoChanging(value)
                ReportPropertyChanging("t_tipo")
                _t_tipo = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("t_tipo")
                Ont_tipoChanged()
            End If
        End Set
    End Property

    Private _t_tipo As Global.System.Int32
    Private Partial Sub Ont_tipoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ont_tipoChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_autor__t_ida__1273C1CD", "fac_archivo")>
    Public Property fac_archivo() As fac_archivo
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_archivo").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_archivo").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property fac_archivoReference() As EntityReference(Of fac_archivo)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_archivo")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_autor__t_ida__1273C1CD", "fac_archivo", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_autor__t_usu__1367E606", "fac_persona")>
    Public Property fac_persona() As fac_persona
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_persona").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_persona").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property fac_personaReference() As EntityReference(Of fac_persona)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_persona")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_persona", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_comentario")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_comentario
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_comentario.
    ''' </summary>
    ''' <param name="c_idarchivo">Valor inicial de la propiedad c_idarchivo.</param>
    ''' <param name="c_usuario">Valor inicial de la propiedad c_usuario.</param>
    ''' <param name="c_texto">Valor inicial de la propiedad c_texto.</param>
    ''' <param name="c_estado">Valor inicial de la propiedad c_estado.</param>
    Public Shared Function Createfac_comentario(c_idarchivo As Global.System.String, c_usuario As Global.System.String, c_texto As Global.System.String, c_estado As Global.System.Int32) As fac_comentario
        Dim fac_comentario as fac_comentario = New fac_comentario
        fac_comentario.c_idarchivo = c_idarchivo
        fac_comentario.c_usuario = c_usuario
        fac_comentario.c_texto = c_texto
        fac_comentario.c_estado = c_estado
        Return fac_comentario
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property c_idarchivo() As Global.System.String
        Get
            Return _c_idarchivo
        End Get
        Set
            If (_c_idarchivo <> Value) Then
                Onc_idarchivoChanging(value)
                ReportPropertyChanging("c_idarchivo")
                _c_idarchivo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("c_idarchivo")
                Onc_idarchivoChanged()
            End If
        End Set
    End Property

    Private _c_idarchivo As Global.System.String
    Private Partial Sub Onc_idarchivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onc_idarchivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property c_usuario() As Global.System.String
        Get
            Return _c_usuario
        End Get
        Set
            If (_c_usuario <> Value) Then
                Onc_usuarioChanging(value)
                ReportPropertyChanging("c_usuario")
                _c_usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("c_usuario")
                Onc_usuarioChanged()
            End If
        End Set
    End Property

    Private _c_usuario As Global.System.String
    Private Partial Sub Onc_usuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onc_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property c_texto() As Global.System.String
        Get
            Return _c_texto
        End Get
        Set
            If (_c_texto <> Value) Then
                Onc_textoChanging(value)
                ReportPropertyChanging("c_texto")
                _c_texto = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("c_texto")
                Onc_textoChanged()
            End If
        End Set
    End Property

    Private _c_texto As Global.System.String
    Private Partial Sub Onc_textoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onc_textoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property c_estado() As Global.System.Int32
        Get
            Return _c_estado
        End Get
        Set
            If (_c_estado <> Value) Then
                Onc_estadoChanging(value)
                ReportPropertyChanging("c_estado")
                _c_estado = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("c_estado")
                Onc_estadoChanged()
            End If
        End Set
    End Property

    Private _c_estado As Global.System.Int32
    Private Partial Sub Onc_estadoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onc_estadoChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_hastags")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_hastags
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_hastags.
    ''' </summary>
    ''' <param name="h_idarchivo">Valor inicial de la propiedad h_idarchivo.</param>
    ''' <param name="h_descripcion">Valor inicial de la propiedad h_descripcion.</param>
    Public Shared Function Createfac_hastags(h_idarchivo As Global.System.String, h_descripcion As Global.System.String) As fac_hastags
        Dim fac_hastags as fac_hastags = New fac_hastags
        fac_hastags.h_idarchivo = h_idarchivo
        fac_hastags.h_descripcion = h_descripcion
        Return fac_hastags
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property h_idarchivo() As Global.System.String
        Get
            Return _h_idarchivo
        End Get
        Set
            If (_h_idarchivo <> Value) Then
                Onh_idarchivoChanging(value)
                ReportPropertyChanging("h_idarchivo")
                _h_idarchivo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("h_idarchivo")
                Onh_idarchivoChanged()
            End If
        End Set
    End Property

    Private _h_idarchivo As Global.System.String
    Private Partial Sub Onh_idarchivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onh_idarchivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property h_descripcion() As Global.System.String
        Get
            Return _h_descripcion
        End Get
        Set
            Onh_descripcionChanging(value)
            ReportPropertyChanging("h_descripcion")
            _h_descripcion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("h_descripcion")
            Onh_descripcionChanged()
        End Set
    End Property

    Private _h_descripcion As Global.System.String
    Private Partial Sub Onh_descripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onh_descripcionChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_hasta__h_ida__117F9D94", "fac_archivo")>
    Public Property fac_archivo() As fac_archivo
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_archivo").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_archivo").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property fac_archivoReference() As EntityReference(Of fac_archivo)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_archivo")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of fac_archivo)("FACSHAREDModel.FK__fac_hasta__h_ida__117F9D94", "fac_archivo", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_persona")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_persona
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_persona.
    ''' </summary>
    ''' <param name="p_usuario">Valor inicial de la propiedad p_usuario.</param>
    Public Shared Function Createfac_persona(p_usuario As Global.System.String) As fac_persona
        Dim fac_persona as fac_persona = New fac_persona
        fac_persona.p_usuario = p_usuario
        Return fac_persona
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property p_usuario() As Global.System.String
        Get
            Return _p_usuario
        End Get
        Set
            If (_p_usuario <> Value) Then
                Onp_usuarioChanging(value)
                ReportPropertyChanging("p_usuario")
                _p_usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("p_usuario")
                Onp_usuarioChanged()
            End If
        End Set
    End Property

    Private _p_usuario As Global.System.String
    Private Partial Sub Onp_usuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_primer_nombre() As Global.System.String
        Get
            Return _p_primer_nombre
        End Get
        Set
            Onp_primer_nombreChanging(value)
            ReportPropertyChanging("p_primer_nombre")
            _p_primer_nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_primer_nombre")
            Onp_primer_nombreChanged()
        End Set
    End Property

    Private _p_primer_nombre As Global.System.String
    Private Partial Sub Onp_primer_nombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_primer_nombreChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_segundo_nombre() As Global.System.String
        Get
            Return _p_segundo_nombre
        End Get
        Set
            Onp_segundo_nombreChanging(value)
            ReportPropertyChanging("p_segundo_nombre")
            _p_segundo_nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_segundo_nombre")
            Onp_segundo_nombreChanged()
        End Set
    End Property

    Private _p_segundo_nombre As Global.System.String
    Private Partial Sub Onp_segundo_nombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_segundo_nombreChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_primer_apellido() As Global.System.String
        Get
            Return _p_primer_apellido
        End Get
        Set
            Onp_primer_apellidoChanging(value)
            ReportPropertyChanging("p_primer_apellido")
            _p_primer_apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_primer_apellido")
            Onp_primer_apellidoChanged()
        End Set
    End Property

    Private _p_primer_apellido As Global.System.String
    Private Partial Sub Onp_primer_apellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_primer_apellidoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_segundo_apellido() As Global.System.String
        Get
            Return _p_segundo_apellido
        End Get
        Set
            Onp_segundo_apellidoChanging(value)
            ReportPropertyChanging("p_segundo_apellido")
            _p_segundo_apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_segundo_apellido")
            Onp_segundo_apellidoChanged()
        End Set
    End Property

    Private _p_segundo_apellido As Global.System.String
    Private Partial Sub Onp_segundo_apellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_segundo_apellidoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_password() As Global.System.String
        Get
            Return _p_password
        End Get
        Set
            Onp_passwordChanging(value)
            ReportPropertyChanging("p_password")
            _p_password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_password")
            Onp_passwordChanged()
        End Set
    End Property

    Private _p_password As Global.System.String
    Private Partial Sub Onp_passwordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_passwordChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_correo() As Global.System.String
        Get
            Return _p_correo
        End Get
        Set
            Onp_correoChanging(value)
            ReportPropertyChanging("p_correo")
            _p_correo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("p_correo")
            Onp_correoChanged()
        End Set
    End Property

    Private _p_correo As Global.System.String
    Private Partial Sub Onp_correoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onp_correoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_fecha_crea() As Nullable(Of Global.System.DateTime)
        Get
            Return _p_fecha_crea
        End Get
        Set
            Onp_fecha_creaChanging(value)
            ReportPropertyChanging("p_fecha_crea")
            _p_fecha_crea = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("p_fecha_crea")
            Onp_fecha_creaChanged()
        End Set
    End Property

    Private _p_fecha_crea As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onp_fecha_creaChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onp_fecha_creaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property p_estado() As Nullable(Of Global.System.Int32)
        Get
            Return _p_estado
        End Get
        Set
            Onp_estadoChanging(value)
            ReportPropertyChanging("p_estado")
            _p_estado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("p_estado")
            Onp_estadoChanged()
        End Set
    End Property

    Private _p_estado As Nullable(Of Global.System.Int32)
    Private Partial Sub Onp_estadoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onp_estadoChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_autor__t_usu__1367E606", "fac_autorizacion")>
     Public Property fac_autorizacion() As EntityCollection(Of fac_autorizacion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of fac_autorizacion)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_autorizacion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of fac_autorizacion)("FACSHAREDModel.FK__fac_autor__t_usu__1367E606", "fac_autorizacion", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_ranki__r_usu__108B795B", "fac_ranking")>
     Public Property fac_ranking() As EntityCollection(Of fac_ranking)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of fac_ranking)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_ranking")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of fac_ranking)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_ranking", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FACSHAREDModel", Name:="fac_ranking")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class fac_ranking
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto fac_ranking.
    ''' </summary>
    ''' <param name="r_objetivo">Valor inicial de la propiedad r_objetivo.</param>
    ''' <param name="r_usuario">Valor inicial de la propiedad r_usuario.</param>
    Public Shared Function Createfac_ranking(r_objetivo As Global.System.String, r_usuario As Global.System.String) As fac_ranking
        Dim fac_ranking as fac_ranking = New fac_ranking
        fac_ranking.r_objetivo = r_objetivo
        fac_ranking.r_usuario = r_usuario
        Return fac_ranking
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property r_objetivo() As Global.System.String
        Get
            Return _r_objetivo
        End Get
        Set
            If (_r_objetivo <> Value) Then
                Onr_objetivoChanging(value)
                ReportPropertyChanging("r_objetivo")
                _r_objetivo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("r_objetivo")
                Onr_objetivoChanged()
            End If
        End Set
    End Property

    Private _r_objetivo As Global.System.String
    Private Partial Sub Onr_objetivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onr_objetivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property r_usuario() As Global.System.String
        Get
            Return _r_usuario
        End Get
        Set
            If (_r_usuario <> Value) Then
                Onr_usuarioChanging(value)
                ReportPropertyChanging("r_usuario")
                _r_usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("r_usuario")
                Onr_usuarioChanged()
            End If
        End Set
    End Property

    Private _r_usuario As Global.System.String
    Private Partial Sub Onr_usuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onr_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property r_ranking() As Nullable(Of Global.System.Int32)
        Get
            Return _r_ranking
        End Get
        Set
            Onr_rankingChanging(value)
            ReportPropertyChanging("r_ranking")
            _r_ranking = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("r_ranking")
            Onr_rankingChanged()
        End Set
    End Property

    Private _r_ranking As Nullable(Of Global.System.Int32)
    Private Partial Sub Onr_rankingChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onr_rankingChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property r_tipo() As Global.System.String
        Get
            Return _r_tipo
        End Get
        Set
            Onr_tipoChanging(value)
            ReportPropertyChanging("r_tipo")
            _r_tipo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("r_tipo")
            Onr_tipoChanged()
        End Set
    End Property

    Private _r_tipo As Global.System.String
    Private Partial Sub Onr_tipoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onr_tipoChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("FACSHAREDModel", "FK__fac_ranki__r_usu__108B795B", "fac_persona")>
    Public Property fac_persona() As fac_persona
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_persona").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_persona").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property fac_personaReference() As EntityReference(Of fac_persona)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_persona")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of fac_persona)("FACSHAREDModel.FK__fac_ranki__r_usu__108B795B", "fac_persona", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


